In [21]:
def trans_mat1(mat):
    t_mat = [[mat[j][i] for j in range(len(mat))] for i in range(len(mat[0]))]
    return t_mat

In [22]:
def trans_mat2(mat):
    t_mat = zip(*mat)
    return t_mat

In [23]:
import numpy as np
def trans_mat3(mat):
    t_mat = np.array(mat)
    return t_mat.T

In [24]:
def trans_mat4(mat):
    return(np.transpose(mat))

In [25]:
li=[[1,2,3],
   [4,5,6],
   [7,8,9]]
print(trans_mat1(li))
print(trans_mat2(li))
print(trans_mat3(li))
print(trans_mat4(li))

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
